Repository 9oormthon-univ/2024_DANPOON_TEAM_30_BE, pull requests merged in 2024-11, with the labels that each got.

#10 [feat/#9] 전역예외처리
  src/main/java/soon/ready_action/global/exception/ReadyActionException.java
  src/main/java/soon/ready_action/global/exception/dto/response/ErrorResponse.java
  src/main/java/soon/ready_action/global/exception/enums/ErrorCode.java
  src/main/java/soon/ready_action/global/exception/handler/GlobalExceptionHandler.java
Labels: feat

#11 Feat/#8 토큰 재발급
  src/main/java/soon/ready_action/domain/auth/controller/AuthController.java
  src/main/java/soon/ready_action/domain/auth/service/AuthService.java
  src/main/java/soon/ready_action/domain/member/entity/Member.java
  src/main/java/soon/ready_action/global/config/SecurityConfig.java
  src/main/java/soon/ready_action/global/oauth2/jwt/dto/request/ReissueTokenRequest.java
  src/main/java/soon/ready_action/global/oauth2/jwt/filter/JwtAuthorizationFilter.java
  src/main/java/soon/ready_action/global/oauth2/jwt/provider/TokenProvider.java
Labels: feat

#12 Feat/#8 토큰 재발급 로직 수정
  src/main/java/soon/ready_action/domain/auth/service/AuthService.java
  src/main/java/soon/ready_action/global/oauth2/handler/Oauth2KakaoSuccessHandler.java
  src/main/java/soon/ready_action/global/oauth2/service/TokenService.java
Labels: feat

#13 refactor 토큰 필터 추가
  src/main/java/soon/ready_action/global/oauth2/jwt/filter/JwtAccessDeniedHandler.java
  src/main/java/soon/ready_action/global/oauth2/jwt/filter/JwtAuthenticationEntryPoint.java
  src/main/java/soon/ready_action/global/oauth2/jwt/provider/TokenProvider.java
  src/main/java/soon/ready_action/global/provider/CustomObjectMapperProvider.java
Labels: refactor

#15 Docs/auth swagger 추가
  src/main/java/soon/ready_action/domain/auth/controller/AuthController.java
  src/main/java/soon/ready_action/domain/auth/controller/AuthDocsController.java
  src/main/java/soon/ready_action/domain/auth/dto/response/AuthResponse.java
  src/main/java/soon/ready_action/global/config/SecurityConfig.java
  src/main/java/soon/ready_action/global/config/SwaggerConfig.java
  src/main/java/soon/ready_action/global/exception/dto/response/ErrorResponse.java
  src/main/java/soon/ready_action/global/oauth2/jwt/dto/request/ReissueTokenRequest.java
  src/main/java/soon/ready_action/global/oauth2/jwt/dto/response/TokenResponse.java
  src/main/java/soon/ready_action/global/oauth2/jwt/filter/JwtAuthorizationFilter.java
Labels: docs

#16 [feat/#14] 자립지식 전체 및 상세조회
  src/main/java/soon/ready_action/domain/knowledge/controller/KnowledgeController.java
  src/main/java/soon/ready_action/domain/knowledge/dto/KnowledgeResponse.java
  src/main/java/soon/ready_action/domain/knowledge/repository/KnowledgeRepository.java
  src/main/java/soon/ready_action/domain/knowledge/service/KnowledgeService.java
Labels: feat

#18 [Feat/#17] 자립지식 Swagger 구현
  src/main/java/soon/ready_action/domain/knowledge/controller/KnowledgeController.java
Labels: feat

#20 [feat/#7] 온보딩 구현
  src/main/java/soon/ready_action/domain/auth/controller/AuthController.java
  src/main/java/soon/ready_action/domain/auth/controller/AuthDocsController.java
  src/main/java/soon/ready_action/domain/auth/dto/response/OnboardingWrapperResponse.java
  src/main/java/soon/ready_action/domain/auth/service/AuthService.java
  src/main/java/soon/ready_action/domain/category/entity/Category.java
  src/main/java/soon/ready_action/domain/category/repository/CategoryJpaRepository.java
  src/main/java/soon/ready_action/domain/category/repository/CategoryRepository.java
  src/main/java/soon/ready_action/domain/diagnosis/controller/DiagnosisController.java
  src/main/java/soon/ready_action/domain/diagnosis/controller/DiagnosisDocsController.java
  src/main/java/soon/ready_action/domain/diagnosis/dto/QuestionDataLoadDto.java
  src/main/java/soon/ready_action/domain/diagnosis/dto/request/CategoryWithDiagnosisRequest.java
  src/main/java/soon/ready_action/domain/diagnosis/dto/response/OnboardingQuestionResponse.java
  src/main/java/soon/ready_action/domain/diagnosis/entity/AnswerType.java
  src/main/java/soon/ready_action/domain/diagnosis/entity/DiagnosisCategoryScore.java
  src/main/java/soon/ready_action/domain/diagnosis/entity/DiagnosisQuestion.java
  src/main/java/soon/ready_action/domain/diagnosis/entity/DiagnosisResult.java
  src/main/java/soon/ready_action/domain/diagnosis/repository/DiagnosisCategoryScoreRepository.java
  src/main/java/soon/ready_action/domain/diagnosis/repository/DiagnosisQuestionRepository.java
  src/main/java/soon/ready_action/domain/diagnosis/repository/DiagnosisResultRepository.java
  src/main/java/soon/ready_action/domain/diagnosis/repository/jpa/diagnosisCategoryScoreJpaRepository.java
  src/main/java/soon/ready_action/domain/diagnosis/repository/jpa/diagnosisQuestionJpaRepository.java
  src/main/java/soon/ready_action/domain/diagnosis/repository/jpa/diagnosisResultJpaRepository.java
  src/main/java/soon/ready_action/domain/diagnosis/service/DiagnosisService.java
  src/main/java/soon/ready_action/domain/member/dto/request/MemberAdditionalInfoRequest.java
  src/main/java/soon/ready_action/domain/member/entity/Member.java
  src/main/java/soon/ready_action/domain/membercategory/entity/MemberCategory.java
  src/main/java/soon/ready_action/domain/membercategory/repository/MemberCategoryJpaRepository.java
  src/main/java/soon/ready_action/domain/membercategory/repository/MemberCategoryRepository.java
  src/main/java/soon/ready_action/domain/membercategory/service/MemberCategoryService.java
  src/main/java/soon/ready_action/global/config/SecurityConfig.java
  src/main/java/soon/ready_action/global/exception/AnswerTypeNotFoundException.java
  src/main/java/soon/ready_action/global/exception/CategoryNotFoundException.java
  src/main/java/soon/ready_action/global/exception/DiagnosisQuestionNotFoundException.java
  src/main/java/soon/ready_action/global/exception/ForbiddenException.java
  src/main/java/soon/ready_action/global/exception/enums/ErrorCode.java
  src/main/java/soon/ready_action/global/loader/CategoryLoader.java
  src/main/java/soon/ready_action/global/loader/QuestionLoader.java
  src/main/java/soon/ready_action/global/oauth2/jwt/filter/JwtAuthorizationFilter.java
  src/main/java/soon/ready_action/global/oauth2/jwt/provider/TokenProvider.java
  src/main/java/soon/ready_action/global/oauth2/service/TokenService.java
  src/main/java/soon/ready_action/global/provider/CustomObjectMapperProvider.java
  src/main/java/soon/ready_action/global/provider/DataLoader.java
  src/main/resources/data.json
Labels: feat

#21 [feat/#7] jwt 필터 변경
  src/main/java/soon/ready_action/global/config/SecurityConfig.java
Labels: feat

#29 [Feat/#19] 프로그램 기능 구현
  src/main/java/soon/ready_action/domain/knowledge/dto/KnowledgeResponse.java
  src/main/java/soon/ready_action/domain/knowledge/service/KnowledgeService.java
  src/main/java/soon/ready_action/domain/program/controller/ProgramController.java
  src/main/java/soon/ready_action/domain/program/dto/ProgramResponse.java
  src/main/java/soon/ready_action/domain/program/dto/ProgramSearchResponse.java
  src/main/java/soon/ready_action/domain/program/entity/Program.java
  src/main/java/soon/ready_action/domain/program/repository/ProgramRepository.java
  src/main/java/soon/ready_action/domain/program/service/ProgramService.java
Labels: feat

#31 [feat/#30] 챗봇 문답 전송 기능 구현
  src/main/java/soon/ready_action/domain/chatbot/controller/ChatbotController.java
  src/main/java/soon/ready_action/domain/chatbot/dto/request/ChatbotRequest.java
  src/main/java/soon/ready_action/domain/chatbot/dto/response/ChatbotResponse.java
  src/main/java/soon/ready_action/domain/chatbot/repository/ChatbotRepository.java
  src/main/java/soon/ready_action/domain/chatbot/service/ChatbotService.java
Labels: feat

#33 [feat/#28] 자가진단 기능 구현
  src/main/java/soon/ready_action/domain/diagnosis/controller/DiagnosisController.java
  src/main/java/soon/ready_action/domain/diagnosis/controller/DiagnosisDocsController.java
  src/main/java/soon/ready_action/domain/diagnosis/dto/request/CategoryWithDiagnosisRequest.java
  src/main/java/soon/ready_action/domain/diagnosis/dto/request/DiagnosisQuestionPaginationRequest.java
  src/main/java/soon/ready_action/domain/diagnosis/dto/response/DiagnosisQuestionPaginationResponseWrapper.java
  src/main/java/soon/ready_action/domain/diagnosis/dto/response/DiagnosisQuestionResponse.java
  src/main/java/soon/ready_action/domain/diagnosis/repository/DiagnosisQuestionRepository.java
  src/main/java/soon/ready_action/domain/diagnosis/repository/jpa/DiagnosisQuestionJpaRepository.java
  src/main/java/soon/ready_action/domain/diagnosis/repository/pagination/DiagnosisQuestionPaginationRepository.java
  src/main/java/soon/ready_action/domain/diagnosis/repository/pagination/DiagnosisQuestionPaginationRepositoryImpl.java
  src/main/java/soon/ready_action/domain/diagnosis/service/DiagnosisService.java
  src/main/java/soon/ready_action/domain/member/entity/Member.java
  src/main/java/soon/ready_action/global/config/QueryDslConfig.java
  src/test/java/soon/ready_action/domain/diagnosis/repository/pagination/DiagnosisQuestionPaginationRepositoryImplTest.java
Labels: feat

#35 [feat/#28] 자가진단 스코어 기능 구현
  src/main/java/soon/ready_action/domain/auth/service/AuthService.java
  src/main/java/soon/ready_action/domain/category/repository/CategoryRepository.java
  src/main/java/soon/ready_action/domain/diagnosis/controller/DiagnosisController.java
  src/main/java/soon/ready_action/domain/diagnosis/controller/DiagnosisDocsController.java
  src/main/java/soon/ready_action/domain/diagnosis/dto/CalculateDiagnosisResult.java
  src/main/java/soon/ready_action/domain/diagnosis/dto/request/CategoryWithDiagnosisRequest.java
  src/main/java/soon/ready_action/domain/diagnosis/dto/response/DiagnosisQuestionResponse.java
  src/main/java/soon/ready_action/domain/diagnosis/entity/DiagnosisCategoryScore.java
  src/main/java/soon/ready_action/domain/diagnosis/entity/DiagnosisResult.java
  src/main/java/soon/ready_action/domain/diagnosis/repository/DiagnosisCategoryScoreRepository.java
  src/main/java/soon/ready_action/domain/diagnosis/repository/DiagnosisRepositoryCustom.java
  src/main/java/soon/ready_action/domain/diagnosis/repository/DiagnosisRepositoryCustomImpl.java
  src/main/java/soon/ready_action/domain/diagnosis/repository/DiagnosisResultRepository.java
  src/main/java/soon/ready_action/domain/diagnosis/repository/jpa/DiagnosisCategoryScoreJpaRepository.java
  src/main/java/soon/ready_action/domain/diagnosis/repository/jpa/DiagnosisResultJpaRepository.java
  src/main/java/soon/ready_action/domain/diagnosis/repository/jpa/diagnosisCategoryScoreJpaRepository.java
  src/main/java/soon/ready_action/domain/diagnosis/repository/jpa/diagnosisResultJpaRepository.java
  src/main/java/soon/ready_action/domain/diagnosis/repository/pagination/DiagnosisQuestionPaginationRepositoryImpl.java
  src/main/java/soon/ready_action/domain/diagnosis/service/DiagnosisQuestionService.java
  src/main/java/soon/ready_action/domain/diagnosis/service/DiagnosisResultService.java
  src/main/java/soon/ready_action/domain/diagnosis/service/DiagnosisScoreService.java
Labels: feat

#39 [feat/#34] 뱃지 추가 기능 구현
  src/main/java/soon/ready_action/domain/badge/controller/BadgeController.java
  src/main/java/soon/ready_action/domain/badge/entity/Badge.java
  src/main/java/soon/ready_action/domain/badge/entity/BadgeType.java
  src/main/java/soon/ready_action/domain/badge/repository/BadgeJpaRepository.java
  src/main/java/soon/ready_action/domain/badge/repository/BadgeRepository.java
  src/main/java/soon/ready_action/domain/badge/service/BadgeService.java
  src/main/java/soon/ready_action/domain/diagnosis/repository/DiagnosisCategoryScoreRepository.java
  src/main/java/soon/ready_action/domain/diagnosis/service/DiagnosisResultService.java
  src/main/java/soon/ready_action/domain/diagnosis/service/DiagnosisScoreService.java
  src/main/java/soon/ready_action/global/exception/BadgeNotFoundException.java
  src/main/java/soon/ready_action/global/exception/enums/ErrorCode.java
Labels: feat

#41 [Feat/#38] Main Page 전용 Data 조회
  src/main/java/soon/ready_action/domain/diagnosis/repository/DiagnosisCategoryScoreRepository.java
  src/main/java/soon/ready_action/domain/diagnosis/service/DiagnosisScoreService.java
  src/main/java/soon/ready_action/domain/knowledge/repository/KnowledgeRepository.java
  src/main/java/soon/ready_action/domain/knowledge/service/KnowledgeService.java
  src/main/java/soon/ready_action/domain/main/controller/MainController.java
  src/main/java/soon/ready_action/domain/main/dto/response/MainResponse.java
  src/main/java/soon/ready_action/domain/main/service/MainService.java
  src/main/java/soon/ready_action/domain/membercategory/repository/MemberCategoryJpaRepository.java
  src/main/java/soon/ready_action/domain/membercategory/repository/MemberCategoryRepository.java
  src/main/java/soon/ready_action/domain/membercategory/service/MemberCategoryService.java
  src/main/java/soon/ready_action/domain/program/controller/ProgramController.java
  src/main/java/soon/ready_action/domain/program/repository/ProgramRepository.java
  src/main/java/soon/ready_action/domain/program/service/ProgramService.java
Labels: feat

#43 [fix/#42] main 프로그램 조회 오류 수정
  src/main/java/soon/ready_action/domain/program/repository/ProgramRepository.java
  src/main/java/soon/ready_action/domain/program/service/ProgramService.java
Labels: fix

#45 [feat/#40] 자가진던 결과 response
  src/main/java/soon/ready_action/domain/badge/service/BadgeService.java
  src/main/java/soon/ready_action/domain/diagnosis/controller/DiagnosisController.java
  src/main/java/soon/ready_action/domain/diagnosis/controller/DiagnosisDocsController.java
  src/main/java/soon/ready_action/domain/diagnosis/dto/CalculateDiagnosisResult.java
  src/main/java/soon/ready_action/domain/diagnosis/dto/response/DiagnosisResultWrapper.java
  src/main/java/soon/ready_action/domain/diagnosis/repository/DiagnosisCategoryScoreRepository.java
  src/main/java/soon/ready_action/domain/diagnosis/service/DiagnosisResultService.java
  src/main/java/soon/ready_action/domain/diagnosis/service/DiagnosisScoreService.java
  src/main/java/soon/ready_action/domain/member/entity/CharacterType.java
  src/main/java/soon/ready_action/domain/member/entity/Member.java
  src/main/java/soon/ready_action/domain/program/dto/response/ProgramResponse.java
  src/main/java/soon/ready_action/domain/program/repository/ProgramRepository.java
  src/main/java/soon/ready_action/domain/program/service/ProgramService.java
  src/main/java/soon/ready_action/global/exception/CharacterTypeNotFoundException.java
  src/main/java/soon/ready_action/global/exception/enums/ErrorCode.java
Labels: feat

#47 자가진단 구현 마스터 병합
  src/main/java/soon/ready_action/domain/badge/controller/BadgeController.java
  src/main/java/soon/ready_action/domain/badge/entity/Badge.java
  src/main/java/soon/ready_action/domain/badge/entity/BadgeType.java
  src/main/java/soon/ready_action/domain/badge/repository/BadgeJpaRepository.java
  src/main/java/soon/ready_action/domain/badge/repository/BadgeRepository.java
  src/main/java/soon/ready_action/domain/badge/service/BadgeService.java
  src/main/java/soon/ready_action/domain/diagnosis/controller/DiagnosisController.java
  src/main/java/soon/ready_action/domain/diagnosis/controller/DiagnosisDocsController.java
  src/main/java/soon/ready_action/domain/diagnosis/dto/CalculateDiagnosisResult.java
  src/main/java/soon/ready_action/domain/diagnosis/dto/response/DiagnosisResultWrapper.java
  src/main/java/soon/ready_action/domain/diagnosis/repository/DiagnosisCategoryScoreRepository.java
  src/main/java/soon/ready_action/domain/diagnosis/service/DiagnosisResultService.java
  src/main/java/soon/ready_action/domain/diagnosis/service/DiagnosisScoreService.java
  src/main/java/soon/ready_action/domain/knowledge/dto/KnowledgeResponse.java
  src/main/java/soon/ready_action/domain/knowledge/repository/KnowledgeRepository.java
  src/main/java/soon/ready_action/domain/knowledge/service/KnowledgeService.java
  src/main/java/soon/ready_action/domain/main/controller/MainController.java
  src/main/java/soon/ready_action/domain/main/dto/response/MainResponse.java
  src/main/java/soon/ready_action/domain/main/service/MainService.java
  src/main/java/soon/ready_action/domain/member/entity/CharacterType.java
  src/main/java/soon/ready_action/domain/member/entity/Member.java
  src/main/java/soon/ready_action/domain/membercategory/repository/MemberCategoryJpaRepository.java
  src/main/java/soon/ready_action/domain/membercategory/repository/MemberCategoryRepository.java
  src/main/java/soon/ready_action/domain/membercategory/service/MemberCategoryService.java
  src/main/java/soon/ready_action/domain/program/controller/ProgramController.java
  src/main/java/soon/ready_action/domain/program/dto/response/ProgramResponse.java
  src/main/java/soon/ready_action/domain/program/dto/response/ProgramSearchResponse.java
  src/main/java/soon/ready_action/domain/program/dto/response/ScrapProgramResponse.java
  src/main/java/soon/ready_action/domain/program/repository/ProgramRepository.java
  src/main/java/soon/ready_action/domain/program/service/ProgramService.java
  src/main/java/soon/ready_action/domain/scrap/controller/ScrapController.java
  src/main/java/soon/ready_action/domain/scrap/entity/Scrap.java
  src/main/java/soon/ready_action/domain/scrap/repository/ScrapRepository.java
  src/main/java/soon/ready_action/domain/scrap/service/ScrapService.java
  src/main/java/soon/ready_action/global/exception/BadgeNotFoundException.java
  src/main/java/soon/ready_action/global/exception/CharacterTypeNotFoundException.java
  src/main/java/soon/ready_action/global/exception/enums/ErrorCode.java
Labels: feat

#48 오류 수정
  src/main/java/soon/ready_action/domain/program/service/ProgramService.java
Labels: chore

#49 [feat/#44] 주거 매물 조회 기능 구현
  src/main/java/soon/ready_action/domain/house/controller/HouseController.java
  src/main/java/soon/ready_action/domain/house/dto/response/HouseResponse.java
  src/main/java/soon/ready_action/domain/house/entity/House.java
  src/main/java/soon/ready_action/domain/house/repository/HouseRepository.java
  src/main/java/soon/ready_action/domain/house/service/HouseService.java
Labels: feat

#52 [fix/#50] 챗봇 질문 유형 수정
  src/main/java/soon/ready_action/domain/chatbot/controller/ChatbotController.java
  src/main/java/soon/ready_action/domain/chatbot/dto/request/ChatbotRequest.java
  src/main/java/soon/ready_action/domain/chatbot/entity/QuestionType.java
  src/main/java/soon/ready_action/domain/chatbot/service/ChatbotService.java
Labels: fix

#57 [fix] 챗봇 answer 컬럼 데이터 타입 명시
  src/main/java/soon/ready_action/domain/chatbot/entity/Chatbot.java
Labels: fix

#64 [fix] program description 컬럼 추가
  src/main/java/soon/ready_action/domain/program/dto/response/ProgramResponse.java
  src/main/java/soon/ready_action/domain/program/entity/Program.java
  src/main/java/soon/ready_action/domain/program/service/ProgramService.java
Labels: fix

#66 fix : oauth2 login error fix
  src/main/java/soon/ready_action/domain/auth/controller/AuthController.java
  src/main/java/soon/ready_action/domain/auth/controller/AuthDocsController.java
  src/main/java/soon/ready_action/domain/auth/dto/response/OnboardingWrapperResponse.java
  src/main/java/soon/ready_action/domain/auth/service/AuthService.java
  src/main/java/soon/ready_action/domain/diagnosis/service/DiagnosisQuestionService.java
  src/main/java/soon/ready_action/domain/diagnosis/service/DiagnosisResultService.java
  src/main/java/soon/ready_action/domain/main/controller/MainController.java
  src/main/java/soon/ready_action/domain/program/service/ProgramService.java
  src/main/java/soon/ready_action/domain/scrap/service/ScrapService.java
  src/main/java/soon/ready_action/global/config/SecurityConfig.java
  src/main/java/soon/ready_action/global/oauth2/dto/CustomOAuth2Member.java
  src/main/java/soon/ready_action/global/oauth2/handler/Oauth2KakaoFailHandler.java
  src/main/java/soon/ready_action/global/oauth2/handler/Oauth2KakaoSuccessHandler.java
  src/main/java/soon/ready_action/global/oauth2/jwt/common/TokenExpiration.java
  src/main/java/soon/ready_action/global/oauth2/jwt/common/TokenType.java
  src/main/java/soon/ready_action/global/oauth2/jwt/dto/request/ReissueTokenRequest.java
  src/main/java/soon/ready_action/global/oauth2/jwt/dto/response/TokenResponse.java
  src/main/java/soon/ready_action/global/oauth2/jwt/filter/JwtAccessDeniedHandler.java
  src/main/java/soon/ready_action/global/oauth2/jwt/filter/JwtAuthenticationEntryPoint.java
  src/main/java/soon/ready_action/global/oauth2/jwt/filter/JwtAuthorizationFilter.java
  src/main/java/soon/ready_action/global/oauth2/jwt/provider/TokenProvider.java
  src/main/java/soon/ready_action/global/oauth2/service/Oauth2KakaoService.java
  src/main/java/soon/ready_action/global/oauth2/service/TokenService.java
  src/main/java/soon/ready_action/global/oauth2/v2/oauth/common/OAuthApiClient.java
  src/main/java/soon/ready_action/global/oauth2/v2/oauth/common/OAuthInfoResponse.java
  src/main/java/soon/ready_action/global/oauth2/v2/oauth/common/OAuthLoginParams.java
  src/main/java/soon/ready_action/global/oauth2/v2/oauth/config/ClientConfig.java
  src/main/java/soon/ready_action/global/oauth2/v2/oauth/exception/OAuthException.java
  src/main/java/soon/ready_action/global/oauth2/v2/oauth/kakao/KakaoApiClient.java
  src/main/java/soon/ready_action/global/oauth2/v2/oauth/kakao/KakaoInfoResponse.java
  src/main/java/soon/ready_action/global/oauth2/v2/oauth/kakao/KakaoLoginParams.java
  src/main/java/soon/ready_action/global/oauth2/v2/oauth/kakao/KakaoTokens.java
  src/main/java/soon/ready_action/global/oauth2/v2/oauth/service/RequestOAuthInfoService.java
Labels: fix

#72 [Fix/#67] 페이징 처리 방식 수정
  src/main/java/soon/ready_action/domain/knowledge/controller/KnowledgeController.java
  src/main/java/soon/ready_action/domain/knowledge/dto/KnowledgeResponse.java
  src/main/java/soon/ready_action/domain/knowledge/repository/KnowledgeRepository.java
  src/main/java/soon/ready_action/domain/knowledge/service/KnowledgeService.java
  src/main/java/soon/ready_action/domain/main/dto/response/MainResponse.java
  src/main/java/soon/ready_action/domain/main/service/MainService.java
  src/main/java/soon/ready_action/domain/program/controller/ProgramController.java
  src/main/java/soon/ready_action/domain/program/dto/response/ProgramResponse.java
  src/main/java/soon/ready_action/domain/program/dto/response/ProgramSearchResponse.java
  src/main/java/soon/ready_action/domain/program/dto/response/ScrapProgramResponse.java
  src/main/java/soon/ready_action/domain/program/repository/ProgramRepository.java
  src/main/java/soon/ready_action/domain/program/service/ProgramService.java
  src/main/java/soon/ready_action/domain/scrap/service/ScrapService.java
Labels: fix
